apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kube
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-kube
  template:
    metadata:
      labels:
        app: hello-kube
    spec:
      containers:
        - name: hello
          image: hashicorp/http-echo:1.0.0
          args:
            - "-text=hello from argocd"
          ports:
            - containerPort: 5678
