apiVersion: v1
kind: Service
metadata:
  name: hello-kube
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: hello-kube
  ports:
    - name: http
      port: 80
      targetPort: 5678
